---
- name: Adding Secret for Logging Operator
  hosts: master
  become: true
  tasks:
     - name:  Create logging secret file
       blockinfile:
         path: /opt/rancher/logging_secret.yaml
         create: yes
         block: | 
             apiVersion: v1
             kind: Secret
             type: kubernetes.io/basic-auth
             metadata:
               name: elastic-cli
             data:
               password: ZWxhc3RpYw==
               username: ZWxhc3RpYw==
              
     - name: Applying the Secret file
       shell: kubectl -n cattle-logging-system apply -f /opt/rancher/logging_secret.yaml
       args:
         chdir: /opt/rancher/
       ignore_errors: True
