- hosts: master
  become: yes
  gather_facts: no
  any_errors_fatal: yes
  tasks:
    - name: Get nodes
      shell: kubectl get nodes
      register: nodes_output
      
    - debug:
        msg: "{{nodes_output.stdout_lines}}"
      
    - name: Set the number of nodes
      set_fact:
        no_nodes: '{{nodes_output.stdout_lines | length}}'
        
    - debug:
         msg: '{{no_nodes}}'    
    - name: Setting master node name
      set_fact:
        masternode: "{{ nodes_output.stdout_lines[1].split()[0]}}"
        
    - name: Labeling the master node
      shell: kubectl label nodes "{{masternode}}" gnbnodename=cumachine  --overwrite
      
    - name: labeling the single machine 
      shell: kubectl label nodes "{{masternode}}" gnbnodename=dumachine  --overwrite
      when: no_nodes|int ==2
    - block:
        
       - name: Setting worker node name
         set_fact:
           workernode: "{{ nodes_output.stdout_lines[2].split()[0]}}"
           
       - name: Labeling the worker node
         shell: kubectl label nodes "{{workernode}}" gnbnodename=dumachine --overwrite
         register: worker_Vfs_out       
      when: 'no_nodes|int > 2'