apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "sriov_netdevice",
                "resourcePrefix": "commscope.com",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "drivers": ["i40evf"]
                }
            }
        ]
    }
