apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "sriov_netdevice",
                "resourcePrefix": "commscope.com",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["1014","1016"],
                    "drivers": ["mlx5_core"]
                }
            }
        ]
    }