---
- name: Save the Image on Master then Copy them to the Worker nodes
  hosts: master
  become: true
  tasks:
    - name: Creates Directory customchange
      file:
        path: /opt/kubernetes/customchange
        state: directory
      
    - name: get the  danm-installer:latest docker image
      shell: wget http://10.206.1.205/5G_Softwares/CentOS/TargetServer/Source/danmimages/danm-installer.tgz
      args:
        chdir: /opt/kubernetes/customchange/
      
    - name: get the danm-cni-plugins:latest docker image
      shell: wget http://10.206.1.205/5G_Softwares/CentOS/TargetServer/Source/danmimages/danm-cni-plugins.tgz
      args:
        chdir: /opt/kubernetes/customchange/
      
    - name: get the webhook:latest docker image
      shell: wget http://10.206.1.205/5G_Softwares/CentOS/TargetServer/Source/danmimages/webhook.tgz
      args:
        chdir: /opt/kubernetes/customchange/      
      
    - name: get the svcwatcher:latest docker image
      shell: wget http://10.206.1.205/5G_Softwares/CentOS/TargetServer/Source/danmimages/svcwatcher.tgz
      args:
        chdir: /opt/kubernetes/customchange/
    
    - name: get the netwatcher:latest docker image
      shell: wget http://10.206.1.205/5G_Softwares/CentOS/TargetServer/Source/danmimages/netwatcher.tgz
      args:
        chdir: /opt/kubernetes/customchange/