---
- name: Create file /etc/cni/net.d/00-danm.conf and copy to all worker node
  hosts: master
  become: true
  any_errors_fatal: yes
  tasks:      
    - name: Create file /etc/cni/net.d/00-danm.conf
      shell: |
        cat > /etc/cni/net.d/00-danm.conf <<EOF
        {
        "cniVersion": "0.3.1",
        "name": "meta_cni",
        "name_comment": "Mandatory parameter, but can be anything",
        "type": "danm",
        "type_comment": "Mandatory parameter according to CNI spec, MUST be set to danm",
        "kubeconfig": "/etc/kubernetes/kubeconfig/danmc.yml",
        "kubeconfig_comment": "Mandatory parameter, must point to a valid kubeconfig file containing the necessary RBAC setting for DANM's service account",
        "cniDir": "/etc/cni/net.d",
        "cniDir_comment": "Optional parameter, if defined CNI config files for static delegates are searched here. Default value is /etc/cni/net.d",
        "namingScheme": "legacy",
        "namingScheme_comment": "Optional parameter, if it is set to legacy container network interface names are set exactly to DanmNet.Spec.Options.container_prefix, otherwise prefix simply behaves as a prefix and is suffixed with a sequence ID. Default value is empty (e.g. not legacy)"
        }
        EOF