---
- name: Task [1-3] Base OS preparation
  hosts: all
  become: true
  gather_facts : no
  any_errors_fatal: yes
  tasks:
    - name: Disable SELinux
      shell: "setenforce 0 ; sed -i 's/^SELINUX=.*$/SELINUX=disabled/' /etc/selinux/config"

