---
- hosts: all

  tasks:
#  - name: docker remove containers
#    shell: sudo docker rm `docker ps -a -q`
#    ignore_errors: True
#
#  - name: docker remove images
#    shell: sudo docker rmi `docker images -q`
#    ignore_errors: True
    
  - name: Resetting the cluster
    shell: kubeadm reset -f 
    
  - name: yum remove
    shell: sudo yum -y remove kubeadm kubectl kubelet kubernetes-cni kube*
    
  - name: yum autoremove
    shell: sudo yum -y autoremove 
    
  - name: Removing Repo File of Kubernetes.
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: absent

  - name: Removing required files
    file:
     path: "{{ item }}"
     state: absent
    with_items:
    - /etc/kubernetes/
    - /etc/cni
    - /var/lib/etcd/
    - $HOME/.kube/
    - /opt/kubernetes
    - /opt/rancher
