---
#- import_playbook: ./Base_os_preparation/Base_OS_machine_preparation_Main_file.yml
- import_playbook: ./Docker_Setup/Docker_Main_file.yaml
- import_playbook: ./Pull_Images/Pull_Docker_Images.yaml
- import_playbook: ./Kubernetes_Setup/Kubernetes_Main_file.yml
- import_playbook: ./Core_DNS/DNS_Config.yaml
- import_playbook: ./DANM_Plugin/Damn_Configuration_Main_file.yml
- import_playbook: ./SRIOV_Plugin/SRIOV_Device_Plugin_Main_file.yml
- import_playbook: ./NFD/Labeling_Nodes.yml
- import_playbook: ./Helm_Repo/Helm_Install_Main_file.yml
- import_playbook: ./Application_bring_up/Application_Pods.yml
#- import_playbook: ./Rancher/Rancher_Main.yaml
